### ISSUE TITLE
Updates to Pull Request Checklist per COE

### ISSUE THREAD

**Issue by mdial89f** [CMSgov/macpro-quickstart-serverless#130]
## Type of Issue:

- [ ] Bug: Something isn't working
- [x] Enhancement: New feature or request
- [ ] Question: Further information is requested (I have a question)

#### Issue Creator Checklist

- [x] The appropriate label (bug, enhancement, question) has been attached to this issue.
- [x] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## Background

There are some new recommended checklist items for PRs.  These new items should be added to the pull request template.

New items:

- Section for how to verify what's in the PR 
- checkbox for:  if/applicable I’ve demo’ed (internally) the code
- checkbox for:  I’ve added automated tests, or I’ve knowingly not added automated tests and accept the risk 

## AC:

- PR template is updated with the above new considerations.

**Comment by mdial89f** [comment]
I think this needs more thought.  I feel we might be treading into "more is more" territory.

**Comment by mdial89f** [comment]
At the moment, I'm against putting demo's as a line item in the PR.  I think there is a high risk of abuse.  
Demos cannot take the place of a meaningful pull request and documentation.
